spring.application.name=employee-api-with-jwt

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pagination. No need to set default page number and page size as PageableDefault does it
spring.data.web.pageable.max-page-size=100
