jwt.secret=PF1qwJviTGAWsp/zf6JdKkeFo38Gk0aTPEWQqJtBbEw=
jwt.expiration=3600000

app.cookie.name=__Host-jwt
app.cookie.secure=true

logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
