jwt.secret=PF1qwJviTGAWsp/zf6JdKkeFo38Gk0aTPEWQqJtBbEw=
jwt.expiration=3600000

app.cookie.name=jwt
app.cookie.secure=false

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
